language: python
python:
  - "2.7"
  - "3.4"
  - "pypy"
# https://github.com/travis-ci/travis-ci/issues/4794
matrix:
  include:
    - python: "3.5"
# command to install dependencies
install:
  - "pip install ."
  - "pip install -r test-requirements.txt"
# command to run tests
script: nosetests
